name: Testing
on: workflow_dispatch
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.GA_DEPLOY_KEY }}
          ssh-strict: false
#      - uses: webfactory/ssh-agent@v0.4.1
#        with:
#          ssh-private-key: ${{ secrets.GA_DEPLOY_KEY }}
#      - name: Do commit stuff
#        run: ./actions.sh
#        env:
#          GA_DEPLOY_KEY: ${{ secrets.GA_DEPLOY_KEY }}
      - name: Invoke hook
        run: curl -X POST https://${{ secrets.WEBHOOK_USER }}:${{ secrets.WEBHOOK_USER_PASS }}@WEBHOOK_URL