name: Snapshot deploy
on: 
  push:
    branches: [devel]
jobs:
  deploy-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Do commit stuff
        run: ./actions.sh
